// Code generated by testdata/gendata.sh DO NOT EDIT.
package dl

//Generated Hashes
const MD5_VALID = "f25eb2f56cad9ff59dff0e9dd2b64251"
const MD5_MISMATCH = "ca76fb0fd2687c40183592aa6861cb0c"
const MD5_INVALID = "25eb2f56cad9ff59dff0e9dd2b64251"

