// Code generated by testdata/gendata.sh DO NOT EDIT.
package dl

//Generated Hashes
const SHA1_VALID = "b5db34c1b59b6e0c223b103ba52967dbb59c2f8b"
const SHA1_MISMATCH = "c5bc2709f03f9f2286b210b00e28ae713b2953ed"
const SHA1_INVALID = "5db34c1b59b6e0c223b103ba52967dbb59c2f8b"

