// Code generated by testdata/gendata.sh DO NOT EDIT.
package dl

//Generated Hashes
const SHA256_VALID = "c7ff397df263ecbf0af7b717affa95c6a19fd784dbd20a210190cd5402556177"
const SHA256_MISMATCH = "c6528e2cacf8b0fa2142a70a29959ca7ff768a4a6bddec0239e33725ac9bbd77"
const SHA256_INVALID = "7ff397df263ecbf0af7b717affa95c6a19fd784dbd20a210190cd5402556177"

